AmsmProject/AmsmProject/Controllers/AmsmHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmsmProject.Controllers
{
   // [RequireHttps]
    //kontroler za prikazuvanje na HomePage,AdminPage,Avtoskoli 
    public class AmsmHomeController : Controller
    {

        [AllowAnonymous]
        //
        // GET: /AmsmHome/
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "User,Admin")]
        public ActionResult HomePage()
        {
            return View();
        }

         [Authorize(Roles = "Admin")]
        public ActionResult AdminPage()
        {
            return View();
        }

        [AllowAnonymous]
         public ActionResult Avtoshkoli()
         {
             return View();
         }
	}
}

AmsmProject/AmsmProject/Controllers/TeoretskiDelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmsmProject.Models;
using AmsmProject.DAL;
using PagedList;
using PagedList;

namespace AmsmProject.Controllers
{
    [RequireHttps]
   //kontroler koj sluzi za rabota so kandidati koj zakazuvaat za teoretski del
    public class TeoretskiDelController : Controller
    {
        private AmsmContext db = new AmsmContext();

        //metod koj gi prikazuva kandidatite za teoretski del
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int? page, string searchString)
        {


            var candidates = from c in db.CandidatesTP select c;

            candidates = candidates.OrderByDescending(c => c.date);

          

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));


           
        
        }

        //prikazi gi kandidatite za teoretski del filtrirani po datum 
        [HttpPost]
        [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/
        public ActionResult Index(string searchString, int? page)
        {
          
            var candidates = from c in db.CandidatesTP
                           select c;

            if (!String.IsNullOrEmpty(searchString))
            {

                string day = searchString.Substring(0, 2);
                string month = searchString.Substring(3, 2);
                if (day.StartsWith("0"))
                {
                    day = day.Substring(1, 1);
                }

                if (month.StartsWith("0"))
                {
                    month = month.Substring(1, 1);
                }

                

                string year = searchString.Substring(6, 4);



                candidates = candidates.Where(c => c.date.Day.ToString().Equals(day) && c.date.Month.ToString().Equals(month) && c.date.Year.ToString().Equals(year));
                    
                   
            }
           // return View(candidates.ToList());

            

            candidates = candidates.OrderByDescending(c => c.date);

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));


          

           
        }

         [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheoryPart theorypart = db.CandidatesTP.Find(id);
            if (theorypart == null)
            {
                return HttpNotFound();
            }
            return View(theorypart);
        }


        [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/Create
        public ActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        // POST: /TeoretskiDel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,EMBG,date,hour,passed,payed")] TheoryPart theorypart)
        {
            if (ModelState.IsValid)
            {
                db.CandidatesTP.Add(theorypart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(theorypart);
        }


        [Authorize(Roles = "User")]
        public ActionResult ZakaziTermin()
        {
            return View();
        }


        //metod za zakuzuvanje na termin za teoretski del
        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult ZakaziTermin([Bind(Include = "date,hour")] TheoryPart theorypart)
        {
            bool exsist = false;
            var mbr = (string)Session["mbr"];

            // var candidate = db.CandidatesTP.Find(mbr);

            List<TheoryPart> list = db.CandidatesTP.ToList();
            foreach (TheoryPart tp in list)
            {
                if (tp.EMBG.Equals(mbr))
                {

                    exsist = true;
                }

            }



            //ako vekje zakazal testovi da nemoze pak da zakaze
            if (exsist)
            {
                return Redirect("https://localhost:44301/Error/Exsist");

            }


            if (ModelState.IsValid)
            {
                List<AmsmInfo> informacii = db.Informations.ToList();


                foreach (AmsmInfo ainfo in informacii)
                {
                    if (ainfo.date == theorypart.date && ainfo.hour == theorypart.hour)
                    {
                        if (ainfo.candidatesTP < 30)
                        {

                            ViewBag.Message = "Успешно закажавте термин";
                            // Session["TheoryPID"] = theorypart.ID;
                            //var mbr = (string)Session["mbr"];
                            theorypart.EMBG = mbr;
                            theorypart.passed = false;
                            theorypart.payed = false;
                            db.CandidatesTP.Add(theorypart);

                            int num = ainfo.candidatesTP;
                            ainfo.candidatesTP = num + 1;




                            db.SaveChanges();

                            TempData["PartName"] = "TeoretskiDel";
                            TempData["Cena"] = "2600";
                            return Redirect("https://localhost:44301/Payment/Pay");


                        }

                        else
                        {
                            ViewBag.Message = "Местата за  тој термин се пополнети.Ве молиме изберете друг термин";
                            return View(theorypart);


                        }

                    }



                }

                ViewBag.Message = "Ве молиме изберете соодветно";
                return View(theorypart);
            }



            return View(theorypart);




        }



        [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheoryPart theorypart = db.CandidatesTP.Find(id);
            if (theorypart == null)
            {
                return HttpNotFound();
            }
            return View(theorypart);
        }



        [Authorize(Roles = "Admin")]
        // POST: /TeoretskiDel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,EMBG,date,hour,passed,payed")] TheoryPart theorypart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(theorypart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(theorypart);
        }



        [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheoryPart theorypart = db.CandidatesTP.Find(id);
            if (theorypart == null)
            {
                return HttpNotFound();
            }
            return View(theorypart);
        }



        [Authorize(Roles = "Admin")]
        // POST: /TeoretskiDel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TheoryPart theorypart = db.CandidatesTP.Find(id);
            db.CandidatesTP.Remove(theorypart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmsmProject/AmsmProject/Views/TeoretskiDel/Create.cshtml
@model AmsmProject.Models.TheoryPart

@{
    ViewBag.Title = "Create";
}

<h3>Внеси кандидат</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Теоретски дел</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <p><b>Матичен број</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMBG)
                @Html.ValidationMessageFor(model => model.EMBG)
            </div>
        </div>

        <div class="form-group">
            <p><b>Датум</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
           <p><b>Час</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.hour)
                @Html.ValidationMessageFor(model => model.hour)
            </div>
        </div>

        <div class="form-group">
            <p><b>Положено</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.passed)
                @Html.ValidationMessageFor(model => model.passed)
            </div>
        </div>

        <div class="form-group">
            <p><b>Платено</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.payed)
                @Html.ValidationMessageFor(model => model.payed)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" style="background-color: yellow; font-family: arial; color: black;font-weight: bold; " value="Креирај" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

AmsmProject/AmsmProject/Views/TeoretskiDel/Delete.cshtml
@model AmsmProject.Models.TheoryPart

@{
    ViewBag.Title = "Delete";
}



<h3>Дали сте сигурни дека сакате да го избршете кандидатот?</h3>
<div>
    <h4>Теоретски дел</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p><b>Матичен број</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMBG)
        </dd>

        <dt>
           <p><b>Датум</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            <p><b>Час</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hour)
        </dd>

        <dt>
            <p><b>Положено</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passed)
        </dd>

        <dt>
            <p><b>Платено</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" style="background-color: yellow; font-family: arial; color: black;font-weight: bold; " value="Избриши" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

AmsmProject/AmsmProject/Views/TeoretskiDel/Details.cshtml
@model AmsmProject.Models.TheoryPart

@{
    ViewBag.Title = "Details";
}


<div>
    <br />
    <h4>Теоретски дел</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            <p><b>Матичен број</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMBG)
        </dd>

        <dt>
            <p><b>Датум</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            <p><b>Час</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hour)
        </dd>

        <dt>
            <p><b>Положено</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.passed)
        </dd>

        <dt>
            <p><b>Платено</b></p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Назад", "Index")
</p>

AmsmProject/AmsmProject/Views/TeoretskiDel/Edit.cshtml
@model AmsmProject.Models.TheoryPart

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br />
        <h4>Теоретски дел</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <p><b>Матичен број</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMBG)
                @Html.ValidationMessageFor(model => model.EMBG)
            </div>
        </div>

        <div class="form-group">
          <p><b>Датум</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            <p><b>Час</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.hour)
                @Html.ValidationMessageFor(model => model.hour)
            </div>
        </div>

        <div class="form-group">
          <p><b>Положено</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.passed)
                @Html.ValidationMessageFor(model => model.passed)
            </div>
        </div>

        <div class="form-group">
            <p><b>Платено</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.payed)
                @Html.ValidationMessageFor(model => model.payed)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" style="background-color: yellow; font-family: arial; color: black;font-weight: bold; " value="Зачувај" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

AmsmProject/AmsmProject/Views/TeoretskiDel/Index.cshtml
@model PagedList.IPagedList<AmsmProject.Models.TheoryPart>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    @{
        ViewBag.Title = "Index";
    }

    <h3>Пријавени кандидати за теоретски дел</h3>
    <br />
    <p>
        @Html.ActionLink("Внеси кандидат", "Create")
    </p>
   <p>
    @Html.ActionLink("Назад", "AdminPage","AmsmHome")
  </p>
    <br />
    @using (Html.BeginForm())
    {
        <p>
            Пребарај по датум: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
    }
    <br />
    <br />
    <br />
    <table class="table">
        <tr>
            <th>
                <p><b>Матичен број</b></p>
            </th>
            <th>
                <p><b>Датум</b></p>
            </th>
            <th>
                <p><b>Час</b></p>
            </th>
            <th>
                <p><b>Положено</b></p>
            </th>
            <th>
                <p><b>Платено</b></p>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EMBG)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.hour)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.passed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.payed)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
<br />
Страна @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) од @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

AmsmProject/AmsmProject/Views/TeoretskiDel/ZakaziTermin.cshtml
@model AmsmProject.Models.TheoryPart

@{
    ViewBag.Title = "Create";
}
<p style="color:gray">asdasd</p>
<h4><center><strong>Страна за закажување на термин за полагање на теоретскиот дел за добивање на возачка дозвола</strong></center></h4>

@using (Html.BeginForm())
{   
    @Html.AntiForgeryToken()

        <hr />
        <div class="row">
            <div class="col-lg-4">
                <p style="color:grey">hidden</p>


                <div class="panel-body">
                    <div class="panel panel-info">
                        <div class="panel-heading" style="background-color: #585858; color: #d9534f"><strong>Следете не!</strong></div>


                        <p style="color:white">
                            Морате да го следите редот за полагање за возачкиот испит.Се започнува со теоретскиот дел,
                            па секој член што ќе го положи овој дел продолжува со двата практични дела.<br />
                            Затоа најпрвин изберете датум кога ќе го полагате теоретскиот дел,па после успешно положен дел
                            изберете си термин и за останатите два дела.И за нив важи истото правило. <br />
                            <h4 style="color: #d9534f"><strong>Ви посакуваме добар успех</strong></h4>
                        </p>


                    </div>
                </div>
            </div>

            <div class="col-lg-4">

                <form class="form-horizontal">
                    <p style="color:red"><b>@ViewBag.Message</b></p>
                    <div class="form-group">
                        <p><b> Изберете датум :</b> </p>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.date)
                            @Html.ValidationMessageFor(model => model.date)
                        </div>
                    </div>

                    <div class="form-group">
                        <p><b>Изберете час : </b></p>
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.hour, new[] {
                                new SelectListItem() {Text = "08:00",Value ="8"},
                                 new SelectListItem() {Text = "10:00",Value ="10"}})
                            @Html.ValidationMessageFor(model => model.hour)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <input type="submit" style="background-color: yellow; font-family: arial; color: black;font-weight: bold; " value="Уплати" class="btn btn-default" />
                        </div>
                    </div>


                </form>
            </div>


            <br />
            <br />
            <br />
            <div class="col-lg-4">
                <table border="0" cellspacing="10" align="right">
                    <tr>
                        <td>
                            <iframe marginwidth="10"
                                    width="370"
                                    height="250"
                                    frameborder="0" style="border:0"
                                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC8uqDJxs3IXfdPIY60TaO_OcaRpGchjGg
    &q=АМСМ+Авто+школа,Skopje+Macedonia"></iframe>
                        </td>
                    </tr>
                </table>
          </div>
        </div>
      

        
        @Html.ActionLink("Назад", "HomePage", "AmsmHome")
 
    
}