AmsmProject/AmsmProject/Controllers/AmsmHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmsmProject.Controllers
{
   // [RequireHttps]
    //kontroler za prikazuvanje na HomePage,AdminPage,Avtoskoli 
    public class AmsmHomeController : Controller
    {

        [AllowAnonymous]
        //
        // GET: /AmsmHome/
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "User,Admin")]
        public ActionResult HomePage()
        {
            return View();
        }

         [Authorize(Roles = "Admin")]
        public ActionResult AdminPage()
        {
            return View();
        }

        [AllowAnonymous]
         public ActionResult Avtoshkoli()
         {
             return View();
         }
	}
}

AmsmProject/AmsmProject/Controllers/Dates2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmsmProject.Models;
using AmsmProject.DAL;
using PagedList;

namespace AmsmProject.Controllers
{

    //kontroler za rabota so datumite za polaganje na vtor prakticen del
    public class Dates2Controller : Controller
    {
        private AmsmContext db = new AmsmContext();


        //gi pirkazuva podatocite od bazata vo tabela
        [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: /AmsmDates2/
        public ActionResult Index(int? page, string searchString)
        {
            
            
            var candidates = from c in db.AmsmInfoPP2 select c;

            candidates = candidates.OrderByDescending(c => c.date);

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));

           // return View(candidates.ToList());
        }


        //gi prikazuva podatocite od bazata filtrirani spored datum dokolku e vnesen

         [HttpPost]
         [Authorize(Roles = "Admin")]
         // GET: /TeoretskiDel/
        public ActionResult Index(string searchString, int? page)
         {
         
           var candidates = from c in db.AmsmInfoPP2
                              select c;

             if (!String.IsNullOrEmpty(searchString))
             {

                 string day = searchString.Substring(0, 2);
                 string month = searchString.Substring(3, 2);
                 if (day.StartsWith("0"))
                 {
                     day = day.Substring(1, 1);
                 }

                 if (month.StartsWith("0"))
                 {
                     month = month.Substring(1, 1);
                 }

                 string year = searchString.Substring(6, 4);
                 candidates = candidates.Where(c => c.date.Day.ToString().Equals(day) && c.date.Month.ToString().Equals(month) && c.date.Year.ToString().Equals(year));


             }
  
              candidates = candidates.OrderByDescending(c => c.date);

             int pageSize = 5;
             int pageNumber = (page ?? 1);
             return View(candidates.ToPagedList(pageNumber, pageSize));

             }





         [Authorize(Roles = "Admin")]
        // GET: /AmsmDates2/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfoPP2 amsminfopp2 = db.AmsmInfoPP2.Find(id);
            if (amsminfopp2 == null)
            {
                return HttpNotFound();
            }
            return View(amsminfopp2);
        }

         // Strana za vnesuvanje na datum za vtor prakticen del

         [Authorize(Roles = "Admin")]
        // GET: /AmsmDates2/Create
        public ActionResult Create()
        {
            return View();
        }



        //Vnesuvanje na datum za vtor prakticen del
         [Authorize(Roles = "Admin")]
        // POST: /AmsmDates2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="date,hour,place")] AmsmInfoPP2 amsminfopp2)
        {
            if (ModelState.IsValid)
            {
                amsminfopp2.candidatesPP2 = 0;
                db.AmsmInfoPP2.Add(amsminfopp2);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amsminfopp2);
        }



         [Authorize(Roles = "Admin")]
        // GET: /AmsmDates2/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfoPP2 amsminfopp2 = db.AmsmInfoPP2.Find(id);
            if (amsminfopp2 == null)
            {
                return HttpNotFound();
            }
            return View(amsminfopp2);
        }



         [Authorize(Roles = "Admin")]
        // POST: /AmsmDates2/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,date,hour,place,candidatesPP2")] AmsmInfoPP2 amsminfopp2)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amsminfopp2).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amsminfopp2);
        }



         [Authorize(Roles = "Admin")]
        // GET: /AmsmDates2/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfoPP2 amsminfopp2 = db.AmsmInfoPP2.Find(id);
            if (amsminfopp2 == null)
            {
                return HttpNotFound();
            }
            return View(amsminfopp2);
        }


         [Authorize(Roles = "Admin")]
        // POST: /AmsmDates2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmsmInfoPP2 amsminfopp2 = db.AmsmInfoPP2.Find(id);
            db.AmsmInfoPP2.Remove(amsminfopp2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmsmProject/AmsmProject/Controllers/DatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmsmProject.Models;
using AmsmProject.DAL;
using PagedList;

namespace AmsmProject.Controllers
{

    //kontroler za rabota so datumite za polaganje na prv prakticen del i teoretski del
    public class DatesController : Controller
    {
        private AmsmContext db = new AmsmContext();


    //gi pirkazuva podatocite od bazata vo tabela
         [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: /AmsmDates/
        public ActionResult Index(int? page, string searchString)
        {
           var candidates = from c in db.Informations select c;

            candidates = candidates.OrderByDescending(c => c.date);


            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));

            //return View(candidates.ToList());
        }


         //gi prikazuva podatocite od bazata filtrirani spored datum dokolku e vnesen

        [HttpPost]
        [Authorize(Roles = "Admin")]
        // GET: /TeoretskiDel/
         public ActionResult Index(string searchString, int? page)
        {
           var candidates = from c in db.Informations
                             select c;

            if (!String.IsNullOrEmpty(searchString))
            {

                string day = searchString.Substring(0, 2);
                string month = searchString.Substring(3, 2);
                if (day.StartsWith("0"))
                {
                    day = day.Substring(1, 1);
                }

                if (month.StartsWith("0"))
                {
                    month = month.Substring(1, 1);
                }
                 string year = searchString.Substring(6, 4);
                candidates = candidates.Where(c => c.date.Day.ToString().Equals(day) && c.date.Month.ToString().Equals(month) && c.date.Year.ToString().Equals(year));
              }
         
            candidates = candidates.OrderByDescending(c => c.date);
           
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));

           
         }



        //Vnesuvanje na datum 

        [Authorize(Roles = "Admin")]
        // GET: /AmsmDates/Insert
        public ActionResult Insert()
        {
            return View();
        }



          [Authorize(Roles = "Admin")]
        // POST: /AmsmDates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert([Bind(Include = "date,hour")] AmsmInfo amsminfo)
        {
            if (ModelState.IsValid)
            {
                amsminfo.candidatesTP = 0;
                amsminfo.candidatesPP1 = 0;
               


                db.Informations.Add(amsminfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amsminfo);
         
           

             }
        




          [Authorize(Roles = "Admin")]
        // GET: /AmsmDates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfo amsminfo = db.Informations.Find(id);
            if (amsminfo == null)
            {
                return HttpNotFound();
            }
            return View(amsminfo);
        }


          [Authorize(Roles = "Admin")]
        // GET: /AmsmDates/Create
    public ActionResult Create()
        {
            return View();
        }



          [Authorize(Roles = "Admin")]
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,date,hour,candidatesTP,candidatesPP1,candidatesPP2")] AmsmInfo amsminfo)
        {
            if (ModelState.IsValid)
            {
                db.Informations.Add(amsminfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amsminfo);
        }
    

        // GET: /AmsmDates/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfo amsminfo = db.Informations.Find(id);
            if (amsminfo == null)
            {
                return HttpNotFound();
            }
            return View(amsminfo);
        }

        [Authorize(Roles = "Admin")]
        // POST: /AmsmDates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,date,hour,candidatesTP,candidatesPP1,candidatesPP2")] AmsmInfo amsminfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amsminfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amsminfo);
        }

        [Authorize(Roles = "Admin")]
        // GET: /AmsmDates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AmsmInfo amsminfo = db.Informations.Find(id);
            if (amsminfo == null)
            {
                return HttpNotFound();
            }
            return View(amsminfo);
        }

        [Authorize(Roles = "Admin")]
        // POST: /AmsmDates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AmsmInfo amsminfo = db.Informations.Find(id);
            db.Informations.Remove(amsminfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmsmProject/AmsmProject/Views/AmsmHome/AdminPage.cshtml
@{
    ViewBag.Title = "AdminPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Страна за администраторот</h3>
<div>
    @Html.ActionLink("Пријавени кандидати за теоретски дел", "Index", "TeoretskiDel")
</div>
<br />

<div>
    @Html.ActionLink("Пријавени кандидати за прв практичен дел", "Index", "PrvPrakticenDel")

</div>
<br />
<div>
    @Html.ActionLink("Пријавени кандидати за втор практичен дел", "Index", "VtorPrakticenDel")

</div>
<br />

<div>
    @Html.ActionLink("Кандидати", "List", "SignUp")

</div>
<br />





<div>
    @Html.ActionLink("Датуми за теоретски и прв практичен дел", "Index", "Dates")

</div>
<br />
<div>
    @Html.ActionLink("Датуми за втор практичен дел", "Index", "Dates2")

</div>
<br />

AmsmProject/AmsmProject/Views/AmsmHome/Avtoshkoli.cshtml
@{
    ViewBag.Title = "Avtoshkoli";
}


<!DOCTYPE html>
<html ng-app="gemStore">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <link rel="stylesheet" type="text/css" href="Scripts/bootstrap.min.css" />
    <script type="text/javascript" src="../../Scripts/angular.min.js"></script>
    <script type="text/javascript" src="../../Scripts/app.js"></script>

    
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="amsm.css" rel="stylesheet">
   
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <script src="jquery.js"></script>

    <link href="bootstrap-responsive.css" rel="stylesheet" />


</head>

<div class="container">
    <body class="list-group" ng-controller="StoreController as store" >
        <header>
            <h1 class="text-center">Автошколи во Скопје</h1>
            <h2 class="text-center">– детали –</h2>

        </header>
        <div class="list-group-item" ng-repeat="product in store.products" style="background-color: #B0B0B0">
            <h1> <b>{{product.name | uppercase }}</b></h1>
            <h3><em class="pull-right">{{product.price | currency}}</em></h3>

            <!-- Image Gallery  -->
            <div class='gallery' ng-show="product.images.length" ng-controller="GalleryController as gallery">
                <img ng-src="{{product.images[gallery.current]}}" />

            </div>
            <br />
            <p></p>

            <section class="tab" ng-controller="TabController as tab">
                <ul class="nav nav-pills">
                    <li ng-class="{ active: tab.isSet(1) }">
                        <a href ng-click="tab.setTab(1)">Опис</a>
                    </li>

                    <li ng-class="{ active: tab.isSet(2) }">
                        <a href ng-click="tab.setTab(2)">Цена на часови</a>
                    </li>

                    <li ng-class="{active:tab.isSet(3)}">
                        <a href ng-click="tab.setTab(3)">Автомобили</a>
                    </li>

                    <li ng-class="{active:tab.isSet(4)}">
                        <a href ng-click="tab.setTab(4)">Reviews</a>
                    </li>
                </ul>

                <div ng-show="tab.isSet(1)">
                    <h4>Опис:</h4>
                    <blockquote>{{product.description}}</blockquote>
                    <blockquote>{{product.description2}}</blockquote>
                </div>

                <div ng-show="tab.isSet(2)">
                    <h4>Цена на часови:</h4>
                    <blockquote>{{product.priceTab}}</blockquote>
                    <blockquote>{{product.priceTab2}}</blockquote>
                </div>

                <div ng-show="tab.isSet(3)">
                    <h4>Автомобили кои се нудат:</h4>
                    <blockquote>
                        <ul class="list-inline thumbs">
                         <li class="thumbnail" ng-repeat="image in product.imagesThumb">
        <img ng-src="{{image}}" />
    </li>

</ul>
                    </blockquote>
                </div>

                <!--  Review Tab's Content  -->
                <div ng-show="tab.isSet(4)">
                    <!--  Product Reviews List -->
                    <ul>
                        <h4>Reviews:</h4>
                        <li ng-repeat="review in product.reviews">
                            <blockquote>
                                <strong>Оцена: {{review.stars}} -</strong>
                                {{review.body}}
                                <cite class="clearfix">— {{review.author}}</cite>
                            </blockquote>
                        </li>
                    </ul>

                    <!--  Review Form -->
                    <form ng-submit="reviewCtrl.addReview(product)" ng-controller="ReviewController as reviewCtrl" name="reviewForm">

                        <!--  Live Preview -->
                        <blockquote>
                            <strong>Оцена: {{reviewCtrl.review.stars}} </strong>
                            {{reviewCtrl.review.body}}
                            <cite class="clearfix">—{{reviewCtrl.review.author}}</cite>
                        </blockquote>

                        <!--  Review Form -->
                        <h4>Сподели го јавно твоето мислење за автошколата:</h4>
                        <fieldset class="form-group">
                            <select ng-model="reviewCtrl.review.stars" class="form-control" ng-options="stars for stars in [5,4,3,2,1]" title="Stars">
                                <option value="">Оцени ги услугите на автошколата</option>
                            </select>
                        </fieldset>
                        <fieldset class="form-group">
                            <textarea ng-model="reviewCtrl.review.body" class="form-control" placeholder="Напиши го твојот коментар" title="Review"></textarea>
                        </fieldset>
                        <fieldset class="form-group">
                            <input ng-model="reviewCtrl.review.author" type="email" class="form-control" placeholder="slobodanka@example.org" title="Email" />
                        </fieldset>
                        <fieldset class="form-group">
                            <input type="submit" class="btn btn-primary pull-right" value="Submit Review" />
                        </fieldset>
                    </form>
                </div>
            </section>
        </div>
    </body>
    </div>
</html>

AmsmProject/AmsmProject/Views/AmsmHome/HomePage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>
</head>
<body>
    <p style="color:gray">afasfd</p>

    <h2><center>АМСМ Електронско пријавување</center></h2>

    <div>

        <div class="fb-like" data-href="https://www.facebook.com/AMSM.Clenstvo" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    </div>
        <div class="panel-body">
            <div class="panel panel-info">
                <div class="panel-heading"><strong>@Html.ActionLink("Закажи за теоретски дел", "ZakaziTermin", "TeoretskiDel")</strong></div>
                <div class="panel-body">
                    <p style="color:black ">
                        Теоретската обука во Автошколите ја изведува висококвалификуван предавач по теоретска настава, кој во своето долгогодишно работно искуство обучил повеќе од 3.000 кандидати.
                        За потребите на теоретската обука,располагаме со модерно опремена и целосно комјутеризирана училница, во која со помош на различни помошни средства кандидатите полесно го совладуваат материјалот и соодветно се подготвуваат за полагање на испитот за познавање на теоретските сообраќајни правила и прописи.
                    </p>
                </div>
            </div>

            <div class="panel panel-warning">
                <div class="panel-heading"><strong>@Html.ActionLink("Закажи за прв практичен дел", "ZakaziTermin", "PrvPrakticenDel")</strong> </div>
                <p style="color:black">
                    Практичната обука во Авто Школа Мобилити, која се изведува на најсовремени, климатизирани и комплетно опремени возила: Volkswagen Polo, Toyota Yaris, Mazda 2, Suzuki Alto, Hyundai i10,
                    ќе Ви помогне за најдобра проценка во сите идни сообраќајни ситуации и ќе Ви овозможи самоуверено,
                    безбедно и сигурно урбано возење.
                </p>
                <div class="panel-body">
                    <p>
                </div>
            </div>


            <div class="panel panel-primary">
                <div class="panel-heading"><strong>@Html.ActionLink("Закажи за втор практичен дел", "ZakaziTermin", "VtorPrakticenDel")</strong></div>
                <div class="panel-body">
                    <p style="color: black">Изборот  за место каде би сакале да се обучувате,термини,возило и инструктор ќе придонесат за ваша комплетна поддршка.</p>
                </div>
            </div>
         
        </div>
    <table border="0" cellspacing="10" align="right">
        <tr>
            <td>
                <iframe align="center" marginwidth="10"
                        width="400"
                        height="250"
                        frameborder="0" style="border:0"
                        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC8uqDJxs3IXfdPIY60TaO_OcaRpGchjGg
    &q=АМСМ+Авто+школа,Skopje+Macedonia"></iframe>
            </td>
        </tr>
    </table>


    <iframe align="left" marginwidth="10"
            width="400"
            height="250"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC8uqDJxs3IXfdPIY60TaO_OcaRpGchjGg
    &q=ASUC+Boro+Petrushevski,Skopje+Macedonia"></iframe>

   
    </script>
   </div>
</body>
</html>